#!/usr/bin/env bash
# Prints the running log from the NEXT/ changelog fragments, newest first.
#
# Generated by Verjson/.github scripts/gen-changelog-caller.sh — do not edit by
# hand. Rendering is not implemented here: the canonical changelog contract
# lives in Verjson/.github (ADR 0038) and this repository pins one immutable
# commit of it, shared with .github/workflows/changelog.yml so that what you
# render locally is what CI validates.
set -euo pipefail

CONTRACT_REF="58a82143d28bc84c163d3fed092d8d9425b91a62"
CONTRACT_SHA256="9d2866cd11b600fcd8cfa160f9599b4158f6b18f1b538aa6baf450d0b4b7666b"

# --as-released is the only flag that passes through. It shows what a release
# would write into CHANGELOG/<version>.md, which under ADR 0059 can never be
# edited afterwards — so reading it before merge is the one review step the
# contract asks of a fragment author, and it has to be reachable from the tool
# they are given (#443). Everything else is still refused: this is a renderer,
# not a general front end to a pinned engine.
as_released=
component=
while [ "$#" -gt 0 ]; do
  case "$1" in
    --as-released)
      [ -z "$as_released" ] || { echo "render-next: --as-released was repeated" >&2; exit 2; }
      as_released=--as-released
      shift
      ;;
    --component)
      [ "$#" -ge 2 ] && [ -n "$2" ]         || { echo "render-next: --component requires a value" >&2; exit 2; }
      [ -z "$component" ]         || { echo "render-next: --component was repeated" >&2; exit 2; }
      component="$2"
      shift 2
      ;;
    *)
      echo "render-next: unexpected argument '$1'" >&2
      exit 2
      ;;
  esac
done

root="$(cd "$(dirname "$0")/.." && pwd)"

contract_fail() { echo "render-next: $1" >&2; exit 1; }

contract_digest_of() {
  if command -v sha256sum >/dev/null 2>&1; then
    sha256sum <"$1" | cut -d' ' -f1
  elif command -v shasum >/dev/null 2>&1; then
    shasum -a 256 <"$1" | cut -d' ' -f1
  else
    return 1
  fi
}

# Identity, not existence. The cache path is keyed by commit, which reads as
# content-addressed but is not: nothing stops another tool, a restored CI cache,
# or an interrupted write from leaving different bytes there, and they would then
# be executed as the contract on every run.
contract_is_pinned() {
  [ -f "$1" ] || return 1
  local got
  got="$(contract_digest_of "$1")" || return 1
  [ "$got" = "$CONTRACT_SHA256" ]
}

# CHANGELOG_CONTRACT_PATH selects WHERE the engine comes from — a vendored copy,
# an offline mirror, a warmed CI cache — and cannot select WHAT runs, because the
# override is held to the digest pinned at $CONTRACT_REF. So it stays useful to
# an air-gapped or cache-restoring consumer while the guarantee the renderer is
# sold on ("the same code CI validates with") holds unconditionally (#304).
if [ -n "${CHANGELOG_CONTRACT_PATH:-}" ]; then
  contract="$CHANGELOG_CONTRACT_PATH"
  [ -e "$contract" ] \
    || contract_fail "CHANGELOG_CONTRACT_PATH is $contract, which does not exist"
  contract_is_pinned "$contract" \
    || contract_fail "CHANGELOG_CONTRACT_PATH ($contract) is not the contract pinned at $CONTRACT_REF"
else
  # Stable runner/bootstrap contract: preload
  #   $VERJSON_CHANGELOG_TOOL_CACHE/<commit>/changelog.py
  # or leave the variable unset for the per-user cache. The commit selects the
  # location; CONTRACT_SHA256 still decides whether those bytes may execute.
  cache_root="${VERJSON_CHANGELOG_TOOL_CACHE:-${XDG_CACHE_HOME:-$HOME/.cache}/verjson-changelog}"
  cache_dir="$cache_root/$CONTRACT_REF"
  contract="$cache_dir/changelog.py"
  if ! contract_is_pinned "$contract"; then
    mkdir -p "$cache_dir" \
      || contract_fail "cannot create changelog tool cache directory $cache_dir"
    # mktemp, not a fixed name: concurrent runs share this cache directory.
    tmp="$(mktemp "$cache_dir/.changelog.XXXXXX")" \
      || contract_fail "cannot create a temporary changelog contract in $cache_dir"
    if ! curl -fsSL \
      "https://raw.githubusercontent.com/Verjson/.github/$CONTRACT_REF/scripts/changelog.py" \
      -o "$tmp"; then
      rm -f "$tmp"
      contract_fail "cannot fetch the changelog contract at $CONTRACT_REF and no verified cache entry is available at $contract; preload SHA-256 $CONTRACT_SHA256 and set VERJSON_CHANGELOG_TOOL_CACHE=$cache_root"
    fi
    # Verify before publishing into the cache, so a bad fetch is never persisted
    # for the next run to trust.
    if ! contract_is_pinned "$tmp"; then
      rm -f "$tmp"
      contract_fail "fetched contract does not match the digest pinned at $CONTRACT_REF"
    fi
    mv "$tmp" "$contract" \
      || contract_fail "cannot publish the verified changelog contract to $contract"
  fi
fi

args=(render-next --repo-root "$root")
[ -z "$component" ] || args+=(--component "$component")
[ -z "$as_released" ] || args+=(--as-released)
exec python3 "$contract" "${args[@]}"
