name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  pulumi:
    uses: Verjson/.github/.github/workflows/pulumi-ci.yml@main
    with:
      stacks: '["dev"]'
      validate-command: |
        npm run build
        npm test
      runner: '["ubuntu-latest"]'
    secrets:
      node-auth-token: ${{ secrets.NODE_AUTH_TOKEN || secrets.SUBMODULES_TOKEN || github.token }}
